# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computational Tools for Multiscale Problems
author: Fruzsina Julia Agocs
logo: img/logo.jpeg

exclude_patterns: [README.md]

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - html_image

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/cu-comptools/fall2024 
  branch: main  

launch_buttons:
  binderhub_url: "https://mybinder.org/"  # The URL for your BinderHub (e.g., https://mybinder.org)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: img/logo.png

sphinx:
  config:
    html_extra_path: ["assets"]
    myst_dmath_double_inline: true
    copyright: "2025"
#    html_js_files:
#    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    nb_ipywidgets_js:
        # Load RequireJS, used by the IPywidgets for dependency management
        "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js": 
            "integrity": "sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="
            "crossorigin": "anonymous"
        # Load IPywidgets bundle for embedding.
        "https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@*/dist/embed-amd.js":
            "data-jupyter-widgets-cdn": "https://cdn.jsdelivr.net/npm/"
            "crossorigin": "anonymous"
